name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the 'main' branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Ensure deployment only happens from the main branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # To ensure the latest changes are checked out

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust this to your build output directory
          target_branch: gh-pages  # The branch for GitHub Pages
